// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MudAnalizaFI.Context;

#nullable disable

namespace MudAnalizaFI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250803124634_sablon18")]
    partial class sablon18
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("BrRadnika")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<double>("Duzina")
                        .HasColumnType("float");

                    b.Property<int>("GustinaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaketId")
                        .HasColumnType("int");

                    b.Property<int?>("SablonId")
                        .HasColumnType("int");

                    b.Property<string>("Sifra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Sirina")
                        .HasColumnType("float");

                    b.Property<double>("Tezina")
                        .HasColumnType("float");

                    b.Property<double>("Visina")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("GustinaId");

                    b.HasIndex("PaketId");

                    b.HasIndex("SablonId");

                    b.ToTable("Elementi");
                });

            modelBuilder.Entity("Shared.Gustina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Vrednost")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Gustine");
                });

            modelBuilder.Entity("Shared.Paket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Duzina")
                        .HasColumnType("float");

                    b.Property<string>("SifraPaketa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Sirina")
                        .HasColumnType("float");

                    b.Property<double>("Visina")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Paketi");
                });

            modelBuilder.Entity("Shared.Sablon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sabloni");
                });

            modelBuilder.Entity("Shared.Element", b =>
                {
                    b.HasOne("Shared.Gustina", "Gustina")
                        .WithMany()
                        .HasForeignKey("GustinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Paket", "Paket")
                        .WithMany("Elementi")
                        .HasForeignKey("PaketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Sablon", "Sablon")
                        .WithMany("Elementi")
                        .HasForeignKey("SablonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Gustina");

                    b.Navigation("Paket");

                    b.Navigation("Sablon");
                });

            modelBuilder.Entity("Shared.Paket", b =>
                {
                    b.Navigation("Elementi");
                });

            modelBuilder.Entity("Shared.Sablon", b =>
                {
                    b.Navigation("Elementi");
                });
#pragma warning restore 612, 618
        }
    }
}
