// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MudAnalizaFI.Context;

#nullable disable

namespace MudAnalizaFI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251019111832_jebemga3")]
    partial class jebemga3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("BrRadnika")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<double>("Duzina")
                        .HasColumnType("float");

                    b.Property<int>("GustinaId")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaketId")
                        .HasColumnType("int");

                    b.Property<double?>("Povrsina")
                        .HasColumnType("float");

                    b.Property<int?>("SablonId")
                        .HasColumnType("int");

                    b.Property<string>("Sifra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Sirina")
                        .HasColumnType("float");

                    b.Property<double>("Tezina")
                        .HasColumnType("float");

                    b.Property<double>("Visina")
                        .HasColumnType("float");

                    b.Property<double?>("Vreme")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("GustinaId");

                    b.HasIndex("PaketId");

                    b.HasIndex("SablonId");

                    b.ToTable("Elementi");
                });

            modelBuilder.Entity("Shared.Gustina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SablonId")
                        .HasColumnType("int");

                    b.Property<double>("Vrednost")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SablonId");

                    b.ToTable("Gustine");
                });

            modelBuilder.Entity("Shared.OperacionaLista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("BrzinaLinijeUMinuti")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<double>("DuzinaPaketa")
                        .HasColumnType("float");

                    b.Property<int>("SifraPaketa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OperacionaLista");
                });

            modelBuilder.Entity("Shared.Paket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Duzina")
                        .HasColumnType("float");

                    b.Property<string>("SifraPaketa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Sirina")
                        .HasColumnType("float");

                    b.Property<double>("Visina")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Paketi");
                });

            modelBuilder.Entity("Shared.Sablon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("GustinaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Kvantitet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Vreme")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Sabloni");
                });

            modelBuilder.Entity("Shared.TextFieldItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.Property<int?>("Kvartal")
                        .HasColumnType("int");

                    b.Property<int>("OperacionaListaId")
                        .HasColumnType("int");

                    b.Property<int?>("PodElementId")
                        .HasColumnType("int");

                    b.Property<int?>("RedniBroj")
                        .HasColumnType("int");

                    b.Property<double?>("Vreme")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.HasIndex("OperacionaListaId");

                    b.HasIndex("PodElementId")
                        .IsUnique()
                        .HasFilter("[PodElementId] IS NOT NULL");

                    b.ToTable("TextFieldItems");
                });

            modelBuilder.Entity("Shared.Element", b =>
                {
                    b.HasOne("Shared.Gustina", "Gustina")
                        .WithMany()
                        .HasForeignKey("GustinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Paket", "Paket")
                        .WithMany()
                        .HasForeignKey("PaketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Sablon", "Sablon")
                        .WithMany()
                        .HasForeignKey("SablonId");

                    b.Navigation("Gustina");

                    b.Navigation("Paket");

                    b.Navigation("Sablon");
                });

            modelBuilder.Entity("Shared.Gustina", b =>
                {
                    b.HasOne("Shared.Sablon", null)
                        .WithMany("Gustine")
                        .HasForeignKey("SablonId");
                });

            modelBuilder.Entity("Shared.TextFieldItem", b =>
                {
                    b.HasOne("Shared.Element", "Element")
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shared.OperacionaLista", "OperacionaLista")
                        .WithMany("TextFieldItems")
                        .HasForeignKey("OperacionaListaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Element", "PodElementi")
                        .WithOne()
                        .HasForeignKey("Shared.TextFieldItem", "PodElementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Element");

                    b.Navigation("OperacionaLista");

                    b.Navigation("PodElementi");
                });

            modelBuilder.Entity("Shared.OperacionaLista", b =>
                {
                    b.Navigation("TextFieldItems");
                });

            modelBuilder.Entity("Shared.Sablon", b =>
                {
                    b.Navigation("Gustine");
                });
#pragma warning restore 612, 618
        }
    }
}
